# Site settings
title: Integrity
email: amandavasqeuz616@gmail.com
description: Tax, Life Insurance and Finance
baseurl: "/fractal-jekyll-theme" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site e.g. http://yvesespinosa.com
download_button_url: ""

# Social settings
500px_url:
facebook_url: https://www.facebook.com/profile.php?id=61579096572564
github_url: 
gitlab_url: 
googleplus_url: 
instagram_url:
linkedin_url: www.linkedin.com/in/amanda-vasquez-66075a206
pinterest_url:
twitter_url:  

# Build settings
markdown: kramdown


